
name: Deploy to S3

on:
  push:
    branches: [main]  # or "master" if that's your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # Change if your S3 bucket is in a different region

      - name: Sync files to S3
        run: aws s3 sync . s3://github-s3-deploy --delete --exclude ".git/*" --exclude ".github/*"
